# Generated by Django 3.1.12 on 2024-12-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feast_recipes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
