# Generated by Django 3.1.12 on 2024-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast_recipes', '0003_recipe_recipeinteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveBigIntegerField(default=3, help_text='Ex-3,4,7'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(help_text='Time in minutes'),
        ),
    ]
