# Generated by Django 3.1.12 on 2024-12-30 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast_recipes', '0004_auto_20241230_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='nutritional_info',
        ),
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, help_text='Calories per serving', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(blank=True, help_text='Carbohydrate content in grams', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(blank=True, help_text='Fat content in grams', null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(blank=True, help_text='Protein content in grams', null=True),
        ),
    ]
