# Generated by Django 3.1.12 on 2025-01-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast_recipes', '0006_auto_20250104_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
