# Generated by Django 3.1.12 on 2025-01-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast_recipes', '0007_recipe_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='saved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeinteraction',
            name='interaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('save', 'Save'), ('comment', 'Comment'), ('view', 'View')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
