# Generated by Django 3.1.12 on 2025-01-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feast_recipes', '0008_auto_20250108_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeinteraction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recipeinteraction',
            name='interaction_type',
        ),
        migrations.AddField(
            model_name='recipeinteraction',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeinteraction',
            name='saved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipeinteraction',
            name='shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='procedure',
            field=models.TextField(help_text='Step-by-step instructions for preparing the dish.'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
